### ISSUE TITLE
Draft claim status content for usability testing

### ISSUE THREAD

**Issue by AngelQuicksey** [cagov/ui-claim-tracker#12] opened 2021-03-02 14:53 UTC
### Task
Iterate on claim status database based on feedback and secondary research

### Acceptance Criteria

- Claim status database content is ready to be tested with claimants

**Comment by nicoleslaw** [comment] 2021-03-19 17:01
Closing as a duplicate of https://github.com/cagov/ui-claim-tracker/issues/60

**Closed by nicoleslaw** 2021-03-19 17:01 UTC
Labels: Design, Size: L
